"""empty message

Revision ID: 410e0b56c115
Revises: 
Create Date: 2020-05-18 09:29:25.597063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410e0b56c115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('MedicationPharmacy_medicationId_fkey', 'MedicationPharmacy', type_='foreignkey')
    op.drop_constraint('MedicationPharmacy_pharmacyId_fkey', 'MedicationPharmacy', type_='foreignkey')
    op.create_foreign_key(None, 'MedicationPharmacy', 'Pharmacy', ['pharmacyId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'MedicationPharmacy', 'Medication', ['medicationId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'MedicationPharmacy', type_='foreignkey')
    op.drop_constraint(None, 'MedicationPharmacy', type_='foreignkey')
    op.create_foreign_key('MedicationPharmacy_pharmacyId_fkey', 'MedicationPharmacy', 'Pharmacy', ['pharmacyId'], ['id'])
    op.create_foreign_key('MedicationPharmacy_medicationId_fkey', 'MedicationPharmacy', 'Medication', ['medicationId'], ['id'])
    # ### end Alembic commands ###
